"""add media_file_status table take 2

Revision ID: 0dfb91063d61
Revises: 40ab5d46334b
Create Date: 2026-08-16 15:43:12.538112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfb91063d61'
down_revision: Union[str, Sequence[str], None] = '40ab5d46334b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_file_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_file_id', 'user_id', name='uq_media_file_status_media_user')
    )
    op.create_index(op.f('ix_media_file_status_media_file_id'), 'media_file_status', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_media_file_status_user_id'), 'media_file_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_file_status_user_id'), table_name='media_file_status')
    op.drop_index(op.f('ix_media_file_status_media_file_id'), table_name='media_file_status')
    op.drop_table('media_file_status')
    # ### end Alembic commands ###
