"""add key_bundle table

Revision ID: 411459a24b8b
Revises: 59f7761c4015
Create Date: 2026-09-01 10:35:31.325647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411459a24b8b'
down_revision: Union[str, Sequence[str], None] = '59f7761c4015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('x25519_public', sa.Text(), nullable=False),
    sa.Column('ml_kem_public', sa.Text(), nullable=False),
    sa.Column('ed25519_public', sa.Text(), nullable=False),
    sa.Column('ml_dsa_public', sa.Text(), nullable=False),
    sa.Column('x25519_signature', sa.Text(), nullable=False),
    sa.Column('ml_kem_signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_bundles_user_id'), 'key_bundles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_bundles_user_id'), table_name='key_bundles')
    op.drop_table('key_bundles')
    # ### end Alembic commands ###
