"""add connections table

Revision ID: 59f7761c4015
Revises: 0dfb91063d61
Create Date: 2026-09-01 09:53:56.009055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f7761c4015'
down_revision: Union[str, Sequence[str], None] = '0dfb91063d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_connections_requester_addressee')
    )
    op.create_index(op.f('ix_connections_addressee_id'), 'connections', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_connections_requester_id'), 'connections', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_requester_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_addressee_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
