"""add used_at to invite_code

Revision ID: a87f1136775e
Revises: ebf46919a900
Create Date: 2026-07-20 23:38:11.316490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87f1136775e'
down_revision: Union[str, Sequence[str], None] = 'ebf46919a900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_code', sa.Column('used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_code', 'used_at')
    # ### end Alembic commands ###
