"""add index on message_status user_id

Revision ID: beb13b723217
Revises: 6fee90ebf3cf
Create Date: 2026-08-09 20:49:39.470300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb13b723217'
down_revision: Union[str, Sequence[str], None] = '6fee90ebf3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_status_user_id'), 'message_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_status_user_id'), table_name='message_status')
    # ### end Alembic commands ###
